version: "3.8"

services:
  postgres:
    image: postgres:12-alpine
    container_name: postgres
    env_file:
      - ./.env
    volumes:
      - data:/var/lib/postgresql/data

  backend:
    build: ./.
    container_name: backend
    ports:
      - '3000:3000'
    env_file:
      - ./.env
    command: npm run start:migrate
    depends_on:
      - postgres

volumes:
  data: