version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    env_file:
      - ./.prod.env
    volumes:
      - data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: backend
    ports:
      - '3000:3000'
    env_file:
      - ./.prod.env
    depends_on:
      - postgres

volumes:
  data: